<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1587412267552' stop='1587412270462'>
    <name>Protractor Demo App</name>
    <title>Protractor Demo App</title>
    <test-cases>
        <test-case start='1587412267553' status='passed' stop='1587412270452'>
            <name>should add one and two</name>
            <title>should add one and two</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
        </test-case>
        <test-case start='1587412270452' status='failed' stop='1587412270461'>
            <name>should sub one and two</name>
            <title>should sub one and two</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Failed: pgobj.clickGo1 is not a function</message>
                <stack-trace>TypeError: pgobj.clickGo1 is not a function
                    at UserContext.&lt;anonymous> (/home/gustavopc/Develop/testeProtractor/tests/calculator.js:25:11)
                    at /usr/lib/node_modules/protractor/node_modules/jasminewd2/index.js:112:25
                    at new ManagedPromise (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1077:7)
                    at ControlFlow.promise (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2505:12)
                    at schedulerExecute (/usr/lib/node_modules/protractor/node_modules/jasminewd2/index.js:95:18)
                    at TaskQueue.execute_ (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:3084:14)
                    at TaskQueue.executeNext_ (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:3067:27)
                    at /usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2974:25
                    at /usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:668:7
                    at processTicksAndRejections (internal/process/task_queues.js:97:5)
                From: Task: Run it("should sub one and two") in control flow
                    at UserContext.&lt;anonymous> (/usr/lib/node_modules/protractor/node_modules/jasminewd2/index.js:94:19)
                    at attempt (/usr/lib/node_modules/protractor/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4297:26)
                    at QueueRunner.run (/usr/lib/node_modules/protractor/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4217:20)
                    at QueueRunner.execute (/usr/lib/node_modules/protractor/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4199:10)
                    at Spec.queueRunnerFactory (/usr/lib/node_modules/protractor/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:909:35)
                    at Spec.execute (/usr/lib/node_modules/protractor/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:526:10)
                    at UserContext.fn (/usr/lib/node_modules/protractor/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:5340:37)
                    at attempt (/usr/lib/node_modules/protractor/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4297:26)
                    at QueueRunner.run (/usr/lib/node_modules/protractor/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4217:20)
                    at runNext (/usr/lib/node_modules/protractor/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4257:20)
                From asynchronous test: 
                Error
                    at Suite.&lt;anonymous> (/home/gustavopc/Develop/testeProtractor/tests/calculator.js:17:3)
                    at addSpecsToSuite (/usr/lib/node_modules/protractor/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1107:25)
                    at Env.describe (/usr/lib/node_modules/protractor/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1074:7)
                    at describe (/usr/lib/node_modules/protractor/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4399:18)
                    at Object.&lt;anonymous> (/home/gustavopc/Develop/testeProtractor/tests/calculator.js:3:1)
                    at Module._compile (internal/modules/cjs/loader.js:1156:30)
                    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
                    at Module.load (internal/modules/cjs/loader.js:1000:32)
                    at Function.Module._load (internal/modules/cjs/loader.js:899:14)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>